// Photo captions — copied verbatim from the Airbnb photo tour (host editor), in the same
// order as PHOTOS in script.js (photo-01.jpeg ... photo-46.jpeg).
const PHOTO_CAPTIONS = [
  { fr: "Salon spacieux et lumineux au décor tropical chic, ouvert sur la chambre", en: "Spacious, bright living room with chic tropical decor, opening onto the bedroom" },
  { fr: "Façade du bungalow Serenity au coucher du soleil, entourée de végétation", en: "Bungalow Serenity's façade at sunset, surrounded by greenery" },
  { fr: "Cuisine ouverte entièrement équipée, avec vue sur la végétation", en: "Fully equipped open kitchen with a view over the greenery" },
  { fr: "Votre espace nuit tout confort avec climatisation et/ou ventilateur de plafond — Lit King size : 180x200", en: "Your fully comfortable sleeping space with air conditioning and/or ceiling fan — King-size bed: 180x200" },
  { fr: "Salle de bain avec double vasque en bois et rangements", en: "Bathroom with wooden double vanity and storage" },
  { fr: "Télécommande Smart TV avec Netflix et YouTube\nTélécommande ventilateur\nEt télécommande climatiseur", en: "Smart TV remote with Netflix and YouTube\nFan remote\nAnd AC remote" },
  { fr: "Votre espace cocooning : un grand canapé convertible (canapé de 2,20 m et couchage de 160x190), ventilateur et climatisation", en: "Your cozy space: a large sofa bed (2.20 m sofa, 160x190 sleeping area), fan and air conditioning" },
  { fr: "Salon avec climatiseur, ventilateur et Smart TV", en: "Living room with AC, fan and Smart TV" },
  { fr: "Table basse du salon et petite touche de déco", en: "Living room coffee table with a little decorative touch" },
  { fr: "Canapé spacieux et convertible dans le salon avec ventilateur au plafond et climatisation murale", en: "Spacious sofa bed in the living room with ceiling fan and wall-mounted AC" },
  { fr: "Salon avec canapé convertible — couchage 160x190", en: "Living room with sofa bed — 160x190 sleeping area" },
  { fr: "Vue du salon vers la cuisine ouverte", en: "View from the living room toward the open kitchen" },
  { fr: "Passage du salon vers la chambre, également ventilée et climatisée", en: "Passage from the living room to the bedroom, also fitted with a fan and AC" },
  { fr: "Lit King size (180x200) tout en confort\nChambre avec ventilateur et air conditionné\nGrands placards / dressing", en: "King-size bed (180x200), total comfort\nBedroom with fan and air conditioning\nLarge closets / dressing area" },
  { fr: "Joli coffret dans la chambre pour ranger vos biens personnels : bijoux, papiers\nAvec une console à deux grands tiroirs", en: "Lovely lockbox in the bedroom to store your personal belongings: jewelry, documents\nWith a console table with two large drawers" },
  { fr: "Entrée de la chambre, votre petit nid", en: "Bedroom entrance, your little nest" },
  { fr: "Grande douche italienne", en: "Large walk-in shower" },
  { fr: "Entrée de la salle de bain", en: "Bathroom entrance" },
  { fr: "Machine à laver sur place avec étendoir et pinces à linge", en: "On-site washing machine with drying rack and clothes pegs" },
  { fr: "Une salle de bain aux tons orangés et vert amande pour un doux moment de relaxation", en: "A bathroom in orange and almond-green tones for a soothing moment of relaxation" },
  { fr: "Serviettes invités à disposition", en: "Guest towels provided" },
  { fr: "Transats disponibles pour prendre le soleil, se prélasser et/ou faire une petite sieste\nLes serviettes de plage sont fournies", en: "Sun loungers available for sunbathing, relaxing and/or a little nap\nBeach towels are provided" },
  { fr: "Table extérieure extensible face au lagon et à la vallée", en: "Extendable outdoor table facing the lagoon and the valley" },
  { fr: "Déco de la terrasse extérieure", en: "Outdoor terrace decor" },
  { fr: "Lampe d'ambiance rechargeable — déco extérieure", en: "Rechargeable mood lamp — outdoor decor" },
  { fr: "L'arrivée au bungalow une fois le portail franchi", en: "Arriving at the bungalow once through the gate" },
  { fr: "Entrée privée du bungalow", en: "Private entrance to the bungalow" },
  { fr: "Arrivée à la résidence des Terres Basses", en: "Arrival at the Terres Basses residence" },
  { fr: "Entrée sécurisée des Terres Basses, résidence sécurisée 24h/24", en: "Secure entrance to Terres Basses, a residence secured 24/7" },
  { fr: "Notre jolie vue lagon, nichée dans la végétation", en: "Our lovely lagoon view, nestled in the greenery" },
  { fr: "Espace de vie ouvert : salon et cuisine dans une ambiance chaleureuse", en: "Open living space: living room and kitchen in a warm atmosphere" },
  { fr: "Chambre avec chevet et prises USB", en: "Bedroom with nightstand and USB outlets" },
  { fr: "Enceinte / speaker Bluetooth", en: "Bluetooth speaker" },
  { fr: "Canapé lin et velours", en: "Linen and velvet sofa" },
  { fr: "Fresque murale palmiers", en: "Palm tree mural" },
  { fr: "Vue de la chambre depuis le salon", en: "View of the bedroom from the living room" },
  { fr: "Entrée de la résidence privatisée et sécurisée des Terres Basses", en: "Entrance to the private, secure Terres Basses residence" },
  { fr: "Lit 180x200 cm", en: "180x200 cm bed" },
  { fr: "Cuisine avec four", en: "Kitchen with oven" },
  { fr: "Table de cuisson gaz 3 feux", en: "3-burner gas stove" },
  { fr: "Cuisine moderne, micro-ondes", en: "Modern kitchen, microwave" },
  { fr: "Table gaz et hotte aspirante", en: "Gas stove and extractor hood" },
  { fr: "Presse-agrumes et petits électroménagers assortis", en: "Citrus press and matching small appliances" },
  { fr: "Panier d'accueil avec nos produits locaux made in Saint-Martin", en: "Welcome basket with our local Saint-Martin-made products" },
  { fr: "Hotte aspirante design", en: "Designer extractor hood" },
  { fr: "Entrée de la résidence", en: "Residence entrance" }
];
