// Reviews data — Bungalow Serenity, Terres Basses, Saint-Martin
// Source: guest reviews from the Airbnb listing (https://www.airbnb.fr/rooms/53414747)
const STAY_MAP = {
  "long": { fr: "Séjour de plus d'une semaine", en: "Stay of more than a week" },
  "week": { fr: "Séjour d'environ une semaine", en: "About a week's stay" },
  "short": { fr: "Séjour de quelques nuits", en: "A few nights' stay" },
  "kids": { fr: "Séjour avec enfants", en: "Stay with children" }
};

const REVIEWS = [
{ name:"Elie", meta:{type:"tenure", years:8}, rating:5, date:{fr:"Août 2026", en:"August 2026"}, stay:"long",
  text:{fr:"Le logement est conforme à l'annonce, avec toutes les commodités qui y sont mentionnées. J'ai apprécié l'accueil chaleureux de Carole, la disponibilité et réactivité du duo Patricia/Carole. Même à distance, Patricia a été proactive avec la complicité de Carole sur place et j'ai beaucoup apprécié cela. J'ai aussi apprécié la tranquilité intimiste des lieux. Les gardiens sont courtois et professionnels (cela accroît le sentiment de sécurité). Je pense y revenir...",
  en:"The place matches the listing exactly, with every amenity mentioned. I appreciated Carole's warm welcome and the availability and responsiveness of the Patricia/Carole duo. Even from a distance, Patricia was proactive alongside Carole on site, which I really appreciated. I also loved the intimate, peaceful setting. The security guards are courteous and professional, which adds to the feeling of safety. I think I'll be back..."} },

{ name:"Peter", meta:{type:"location", text:"Waterloo, Canada"}, rating:5, date:{fr:"Juillet 2026", en:"July 2026"}, stay:"long",
  text:{fr:"Patricia a été une hôtesse merveilleuse : sympathique, accueillante, proactive et très réactive, de la réservation au départ. Nous avons séjourné plus d'un mois et avons adoré notre séjour dans le bungalow. L'endroit était paisible, calme, privé et exactement conforme à la description, avec une belle vue et un accès facile à de belles plages. L'arrivée a été très facile et Patricia a toujours été très réactive pour répondre à toutes nos petites questions pendant notre séjour. Nous avons particulièrement apprécié de nous détendre sur le patio et d'utiliser le barbecue. Nous avons passé un merveilleux séjour et nous recommandons vivement le bungalow de Patricia.",
  en:"Patricia was a wonderful host: friendly, welcoming, proactive and very responsive from booking to departure. We stayed over a month and loved our time in the bungalow. The place was peaceful, quiet, private and exactly as described, with a lovely view and easy access to beautiful beaches. Check-in was very easy and Patricia was always quick to answer our small questions during the stay. We especially enjoyed relaxing on the patio and using the barbecue. We had a wonderful stay and highly recommend Patricia's bungalow."} },

{ name:"Manon", meta:{type:"location", text:"Terrebonne, Canada"}, rating:5, date:{fr:"Mars 2026", en:"March 2026"}, stay:"week",
  text:{fr:"Endroit magnifique, on a l'impression d'être seul au monde. J'y retournerais sans hésiter.",
  en:"Beautiful place, it feels like you're the only ones in the world. I would come back without hesitation."} },

{ name:"Esther", meta:{type:"tenure", years:2}, rating:4, date:{fr:"Mai 2026", en:"May 2026"}, stay:"short",
  text:{fr:"Petit cocon au cœur de la résidence des Terres-Basses, très reposant et calme, je recommande !",
  en:"A cozy little nest in the heart of the Terres Basses residence, very restful and quiet — I recommend it!"} },

{ name:"Diana", meta:{type:"location", text:"New York, New York"}, rating:5, date:{fr:"Mai 2026", en:"May 2026"}, stay:"short",
  text:{fr:"C'est vraiment un joyau caché ! J'espère que ça restera comme ça. Extrêmement sûr, calme et à seulement 4 minutes de la plage. Un grand merci à Carole qui nous a accueillis à notre arrivée.",
  en:"This is truly a hidden gem! I hope it stays that way. Extremely safe, quiet, and just 4 minutes from the beach. Big thanks to Carole who welcomed us on arrival."} },

{ name:"Mathieu", meta:{type:"tenure", years:12}, rating:5, date:{fr:"Mars 2026", en:"March 2026"}, stay:"short",
  text:{fr:"Excellente expérience. Le logement est très très bien équipé, nous avons particulièrement apprécié le calme qui y règne. Communication parfaite avec Patricia. À refaire.",
  en:"Excellent experience. The place is extremely well equipped, and we especially appreciated the calm. Perfect communication with Patricia. Would do it again."} },

{ name:"Francois", meta:{type:"location", text:"Sainte-Agathe-des-Monts, Canada"}, rating:5, date:{fr:"Mars 2026", en:"March 2026"}, stay:"long",
  text:{fr:"Nous avons passé un bon séjour. Si vous recherchez un endroit très calme et intime c'est l'endroit idéal, allez-y les yeux fermés. Il vous faut absolument une voiture pour visiter l'île.",
  en:"We had a great stay. If you're looking for a very calm and intimate place, this is it — go for it with confidence. You will definitely need a car to explore the island."} },

{ name:"Dounia", meta:{type:"tenure", years:2}, rating:5, date:{fr:"Février 2026", en:"February 2026"}, stay:null,
  text:{fr:"Un lieu très charmant où vous pourrez vous reposer et profiter pleinement de vos vacances. Un énorme merci à Carole qui nous a accueilli très chaleureusement, nous nous sommes sentis mieux qu'à la maison grâce à elle ! PS : le logement de Patricia est encore plus beau en vrai ;)",
  en:"A very charming place to rest and fully enjoy your vacation. A huge thank you to Carole who welcomed us so warmly — thanks to her we felt even better than at home! PS: Patricia's place is even more beautiful in person ;)"} },

{ name:"BethAnne", meta:{type:"location", text:"Pembroke Pines, Floride"}, rating:5, date:{fr:"Mars 2026", en:"March 2026"}, stay:"short",
  text:{fr:"Le bungalow de Patricia était propre, pittoresque, privé et paisible ! Elle a été très réactive et serviable ! J'ai hâte d'y séjourner à nouveau !",
  en:"Patricia's bungalow was clean, picturesque, private and peaceful! She was very responsive and helpful! I can't wait to stay again!"} },

{ name:"Joey", meta:{type:"location", text:"Wilmington, Caroline du Nord"}, rating:5, date:{fr:"Février 2026", en:"February 2026"}, stay:"week",
  text:{fr:"Nous avons tout aimé de notre séjour chez Patricia. La maison était dans un quartier calme mais à seulement 15 minutes de l'aéroport. Nous nous sommes sentis comme chez nous et reviendrions certainement séjourner ici.",
  en:"We loved everything about our stay at Patricia's. The house was in a quiet neighborhood yet only 15 minutes from the airport. We felt right at home and would definitely come back."} },

{ name:"Lambert", meta:{type:"location", text:"Montréal, Canada"}, rating:5, date:{fr:"Janvier 2026", en:"January 2026"}, stay:"short",
  text:{fr:"Vraiment un bijou. J'y retournerai c'est certain. Tranquille, sécuritaire, très bien décoré, lit confortable, hôte très accueillante.",
  en:"Truly a gem. I will definitely be back. Quiet, safe, beautifully decorated, comfortable bed, very welcoming host."} },

{ name:"Kabir", meta:{type:"location", text:"Ontario, Canada"}, rating:5, date:{fr:"Janvier 2026", en:"January 2026"}, stay:"kids",
  text:{fr:"Patricia est Super-Hôte pour une bonne raison. Elle a été extrêmement serviable et attentionnée. Son logement est situé dans une partie sûre et privée de l'île. Des agents de sécurité surveillent l'activité 24h/24. Bungalow Serenity est une propriété incroyable avec tout ce dont vous avez besoin pour passer un excellent séjour confortable. Le logement est encore plus beau en personne. Très bien conçu et aménagé. Belle terrasse pour profiter de vos repas. Superbe vue sur la montagne et l'eau. Il y a 2 plages pratiquement privées à quelques minutes. Il y avait des chaises longues et des parasols, ainsi qu'une glacière à notre disposition. Parking privé dans une maison fermée. Patricia nous a laissé quelques cadeaux de bienvenue que nous avons reçus à l'arrivée, nous avons beaucoup apprécié ce geste. Nous avons passé un excellent séjour, je peux en dire beaucoup plus mais je vais m'arrêter là. Merci Patricia, nous reviendrons certainement séjourner ici à l'avenir.",
  en:"Patricia is a Superhost for good reason. She was extremely helpful and thoughtful. Her place is in a safe, private part of the island, with security guards monitoring the area 24/7. Bungalow Serenity is an amazing property with everything you need for a comfortable stay. It's even more beautiful in person — very well designed and furnished. Lovely terrace for meals, superb views of the mountain and water. Two practically private beaches just minutes away. Sun loungers, parasols and a cooler were provided. Private parking in a gated property. Patricia left us some welcome gifts, which we really appreciated. We had an excellent stay — I could say much more but I'll stop there. Thank you Patricia, we will definitely be back."} },

{ name:"Jan", meta:{type:"tenure", years:6}, rating:5, date:{fr:"Janvier 2026", en:"January 2026"}, stay:"short",
  text:{fr:"Nous avons séjourné 2 fois chez Patricia lors de notre voyage dans les Caraïbes et nous étions impatients de revenir dans le logement la deuxième fois. Tout était comme décrit sur les photos et tout simplement propre et parfait. Patricia était joignable à tout moment comme lors du 1er séjour et nous a aidés pour toutes les questions. Nous reviendrons à coup sûr !",
  en:"We stayed with Patricia twice during our Caribbean trip and were eager to return the second time. Everything matched the photos and was simply clean and perfect. Patricia was reachable at all times, just like during our first stay, and helped with every question. We will definitely be back!"} },

{ name:"Jean-Francois", meta:{type:"location", text:"Montréal, Canada"}, rating:5, date:{fr:"Décembre 2025", en:"December 2025"}, stay:"week",
  text:{fr:"Nous avons passé un excellent séjour d'une semaine dans cette superbe unité. Tout ce dont nous avions besoin avait été pensé, des instruments de cuisson à la machine Nespresso, des serviettes de plage à la glacière... même le parasol de plage nous a été très utile. Les Terres Basses est un endroit retiré où l'on peut facilement se délier les jambes et accéder à de superbes plages tranquilles avec petits stationnements. Si en plus, comme nous, vous appréciez ne pas avoir de voisins trop proches tout en ayant votre hôte facilement accessible, vous êtes au bon endroit !",
  en:"We had an excellent week's stay in this superb unit. Everything had been thought of, from cookware to the Nespresso machine, from beach towels to the cooler... even the beach umbrella came in handy. Terres Basses is a secluded spot where you can easily stretch your legs and reach beautiful quiet beaches with small parking areas. If, like us, you appreciate not having close neighbors while still having an easily reachable host, this is the right place!"} },

{ name:"Jan", meta:{type:"tenure", years:6}, rating:5, date:{fr:"Décembre 2025", en:"December 2025"}, stay:"short",
  text:{fr:"Nous avons beaucoup apprécié le temps et notre séjour chez Patricia. Patricia était toujours disponible pour nous et nous a aidés à chaque occasion. Le logement correspond exactement aux photos et est tout simplement magnifique avec son emplacement et son design soigné. Nous recommandons le logement à tout le monde et nous nous réjouissons déjà d'être à nouveau invités chez Patricia. Merci pour ce beau séjour.",
  en:"We really enjoyed our time and our stay at Patricia's. Patricia was always available and helped us every time we needed it. The place matches the photos exactly and is simply beautiful, with a great location and careful design. We recommend it to everyone and are already looking forward to staying with Patricia again. Thank you for this wonderful stay."} },

{ name:"Madina", meta:{type:"location", text:"New York, New York"}, rating:5, date:{fr:"Novembre 2025", en:"November 2025"}, stay:"week",
  text:{fr:"J'ai passé un incroyable séjour dans ce magnifique cottage à Terres Basses, Saint-Martin. L'endroit était impeccable, magnifiquement entretenu, avec une excellente disposition qui se sent ouverte et relaxante. La terrasse ensoleillée donnant sur les montagnes verdoyantes était l'un de mes endroits préférés, parfait pour le café du matin ou la détente du soir. Patricia, l'hôte, était incroyablement gentille, réactive et a vraiment pensé à chaque détail. Les cadeaux attentionnés qu'elle a laissés à l'arrivée ont rendu le séjour très spécial. Le chalet est situé dans une communauté luxueuse et sécurisée et l'emplacement est super privé, ce qui a rendu toute l'expérience paisible et relaxante. De plus, il est à quelques minutes de certaines des plus belles plages de l'île. Je n'aurais pas pu demander un meilleur séjour. Hautement recommandé, et je reviendrais absolument séjourner ici !",
  en:"I had an incredible stay in this beautiful cottage in Terres Basses, Saint-Martin. The place was immaculate, beautifully maintained, with an excellent layout that feels open and relaxing. The sunny terrace overlooking green mountains was one of my favorite spots, perfect for morning coffee or evening relaxation. Patricia, the host, was incredibly kind, responsive and really thought of every detail. The thoughtful welcome gifts she left made the stay very special. The cottage is in a secure, upscale community and the location is super private, making the whole experience peaceful and relaxing. Plus, it's minutes from some of the island's best beaches. I couldn't have asked for a better stay. Highly recommended, and I would absolutely come back!"} },

{ name:"Cillian", meta:{type:"tenure", years:13}, rating:5, date:{fr:"Août 2025", en:"August 2025"}, stay:"long",
  text:{fr:"Logement très agréable avec une excellente localisation pour découvrir l'île de Saint-Martin. Le bungalow est très bien équipé ; Patricia a pris soin de mettre à disposition des petites attentions à notre intention. Jon (conjoint de Patricia), Carole et Patricia (à distance) ont toujours été très réactifs et de bons conseils durant notre séjour. Nous recommandons sincèrement ce logement pour vos vacances.",
  en:"Very pleasant place with an excellent location for exploring Saint-Martin. The bungalow is very well equipped; Patricia took care to leave us thoughtful little touches. Jon (Patricia's partner), Carole and Patricia (remotely) were always very responsive and gave great advice during our stay. We genuinely recommend this place for your vacation."} },

{ name:"Virginie", meta:{type:"location", text:"Petit-Bourg, Guadeloupe"}, rating:5, date:{fr:"Juin 2025", en:"June 2025"}, stay:"week",
  text:{fr:"Bungalow idéalement placé à proximité de commerce tout en étant entouré de végétation et isolé des voisins. Chambre, salon et salle de bain spacieux, petit coin cuisine bien équipé et terrasse ventilée. N'hésitez pas, Patricia est très réactive aux demandes et Margaret m'a réservé un accueil très professionnel.",
  en:"Ideally located bungalow, close to shops yet surrounded by greenery and isolated from neighbors. Spacious bedroom, living room and bathroom, a well-equipped little kitchen and a breezy terrace. Don't hesitate — Patricia is very responsive to requests and Margaret gave me a very professional welcome."} },

{ name:"Patrick", meta:{type:"tenure", years:10}, rating:5, date:{fr:"Juin 2025", en:"June 2025"}, stay:"short",
  text:{fr:"Très sympathique et réactif !",
  en:"Very friendly and responsive!"} },

{ name:"Petri", meta:{type:"tenure", years:12}, rating:5, date:{fr:"Mai 2025", en:"May 2025"}, stay:"week",
  text:{fr:"Bungalow vraiment agréable et calme pour séjourner. C'était facile d'accès avec une voiture de location et avec des instructions parfaites. Patricia et Carole étaient des hôtes vraiment gentils. Je recommande vivement !",
  en:"A really pleasant and quiet bungalow to stay in. Easy to reach with a rental car and with perfect instructions. Patricia and Carole were truly kind hosts. I highly recommend it!"} },

{ name:"Martin", meta:{type:"location", text:"Montréal, Canada"}, rating:5, date:{fr:"Janvier 2025", en:"January 2025"}, stay:"long",
  text:{fr:"Nous sommes absolument ravis de notre séjour de deux semaines dans ce joli bungalow. De l'accueil chaleureux de Patricia jusqu'à notre départ, tout était parfait ! Nous avons beaucoup apprécié la beauté, l'intimité et la tranquillité de l'endroit ainsi que le confort du logement d'une propreté irréprochable. Très bien équipé et fonctionnel, nous n'avons manqué de rien. Nous avons passé d'agréables moments de détente sur la terrasse couverte. Bien situé dans un quartier sécurisé, il est facile de partir en voiture à la découverte de l'île et de ses nombreuses et magnifiques plages. Nous espérons y retourner un jour et n'hésiterons pas à recommander cette propriété à nos parents et amis. Merci Patricia pour toutes les petites attentions et la facilité d'entrer en communication avec vous !",
  en:"We were absolutely delighted with our two-week stay in this lovely bungalow. From Patricia's warm welcome to our departure, everything was perfect! We really appreciated the beauty, privacy and tranquility of the place, as well as its spotless comfort. Very well equipped and functional — we lacked nothing. We spent lovely relaxing moments on the covered terrace. Well located in a secure neighborhood, it's easy to drive around exploring the island and its many beautiful beaches. We hope to return one day and will not hesitate to recommend this property to our family and friends. Thank you Patricia for all the little touches and for being so easy to reach."} },

{ name:"Pauline", meta:{type:"tenure", years:10}, rating:5, date:{fr:"Février 2025", en:"February 2025"}, stay:"short",
  text:{fr:"Ce bungalow est un véritable havre de paix et bien situé. Il est très bien équipé, dans les moindres détails, ce qui permet de se sentir à l'aise. Mention spéciale pour la décoration et l'aménagement, tout est de qualité et de très bon goût. Enfin, merci Patricia pour votre chaleureux accueil !",
  en:"This bungalow is a true haven of peace and well located. It is very well equipped down to the smallest details, which makes you feel right at home. Special mention for the decor and layout — everything is high quality and tasteful. Finally, thank you Patricia for your warm welcome!"} },

{ name:"Frédérique", meta:{type:"location", text:"Québec City, Canada"}, rating:5, date:{fr:"Avril 2025", en:"April 2025"}, stay:"week",
  text:{fr:"Le nom parle de lui-même : un bungalow sérénité. Patricia est une hôtesse disponible, accueillante et attentionnée. Elle nous a accueillis personnellement à notre arrivée. Le bungalow est sublime et situé dans un quartier calme et très sécurisé. Il est muni de tout ce qu'on a besoin, de la belle vaisselle, une machine Nespresso, un BBQ. La vue de la terrasse est magnifique. Quel plaisir de prendre le petit déjeuner et le dîner sur la terrasse. Le lit est confortable, l'air climatisé est efficace et la chambre de bain est spacieuse et propre. Patricia nous a offert des petits cadeaux en sus ce qui a ajouté une touche spéciale à notre séjour. Si je retourne à Saint-Martin j'espère avoir le plaisir de rester à nouveau chez Patricia. Enfin, Patricia était toujours disponible pour répondre rapidement à nos questions et à nos messages. L'une de mes plus belles expériences Airbnb !",
  en:"The name speaks for itself: a serenity bungalow. Patricia is an available, welcoming and attentive host. She welcomed us personally on arrival. The bungalow is gorgeous and located in a quiet, very secure neighborhood. It's equipped with everything you need — beautiful dishware, a Nespresso machine, a BBQ. The view from the terrace is magnificent. What a pleasure to have breakfast and dinner on the terrace. The bed is comfortable, the air conditioning works well and the bathroom is spacious and clean. Patricia also gave us little extra gifts which added a special touch to our stay. If I return to Saint-Martin I hope to have the pleasure of staying with Patricia again. Finally, Patricia was always available to quickly answer our questions and messages. One of my best Airbnb experiences!"} },

{ name:"Julie", meta:{type:"tenure", years:4}, rating:5, date:{fr:"Mars 2023", en:"March 2023"}, stay:"week",
  text:{fr:"Ce n'était pas notre première fois sur l'île, mais notre 1re fois chez Patricia. C'est un endroit magnifique avec toutes les commodités, il y a même un BBQ pour faire des repas au bungalow si on désire. L'endroit est très sécuritaire avec des agents, la maison est très tranquille. L'hôtesse, Patricia, est à l'affût de tout et très sympathique. Si nous avions des questions ou des besoins, elle savait y répondre rapidement. C'est vraiment bien situé sur l'île, il y a des restos pas très loin (en voiture). Nous y retournerons, car nous avons adoré notre séjour chez Patricia. Merci pour cette belle semaine.",
  en:"It wasn't our first time on the island, but our first time staying with Patricia. It's a beautiful place with every amenity, there's even a BBQ if you want to cook at the bungalow. The place is very safe with security guards, and the house is very quiet. The host, Patricia, is on top of everything and very friendly. Whenever we had questions or needs, she answered quickly. It's really well located on the island, with restaurants not too far away (by car). We will be back, because we loved our stay with Patricia. Thank you for this wonderful week."} },

{ name:"Ludivine", meta:{type:"location", text:"Le Lamentin, Martinique"}, rating:5, date:{fr:"Avril 2022", en:"April 2022"}, stay:"short",
  text:{fr:"Quel séjour mémorable ! Patricia a pensé à tout dans les moindres détails (le plus impressionnant : les câbles pour recharger votre portable quand vous êtes en voiture, elle les a mis dans le trousseau de clés du bungalow). Le bungalow est d'une propreté exemplaire, bien situé, sécurisé, ventilé, décoré avec goût, c'est un havre de paix. Les petites attentions : on adore !!! Confiture, liqueur et sauce chien. Merci Patricia, prenez vos valises et allez-y les yeux fermés ! Je reviendrai vite. PS : Margareth la femme de ménage, c'est aussi une pépite !!!",
  en:"What a memorable stay! Patricia thought of everything down to the smallest detail (most impressive: the car phone-charging cables, which she attached to the bungalow's keychain). The bungalow is impeccably clean, well located, secure, well ventilated, tastefully decorated — a true haven of peace. The little extra touches: we loved them!!! Jam, liqueur and local sauce chien. Thank you Patricia, pack your bags and go for it with confidence! I'll be back soon. PS: Margareth the housekeeper is also a gem!!!"} },

{ name:"Martine", meta:{type:"tenure", years:10}, rating:5, date:{fr:"Janvier 2022", en:"January 2022"}, stay:"short",
  text:{fr:"Pour qui cherche la tranquillité, le confort et la propreté, ne cherchez pas plus loin. Dans un havre de paix à deux pas des plus belles plages de l'île, on se sent chez soi dans ce ravissant bungalow, décoré avec soin. Tout est prévu avec délicatesse. Literie particulièrement confortable. Je recommande sans réserve.",
  en:"For anyone looking for tranquility, comfort and cleanliness, look no further. In a haven of peace just steps from the island's most beautiful beaches, you feel right at home in this lovely, carefully decorated bungalow. Everything is thoughtfully provided. Particularly comfortable bedding. I recommend it without reservation."} },

{ name:"Melanie", meta:{type:"location", text:"Martinique"}, rating:5, date:{fr:"Avril 2024", en:"April 2024"}, stay:"short",
  text:{fr:"Le logement est particulièrement bien aménagé et équipé. De plus, il est décoré avec goût et très confortable. Il est situé dans un environnement très agréable. Patricia est une hôte extrêmement accueillante et qui sait recevoir. Ma collègue et moi étions ravies d'y passer notre semaine. Il est aussi parfait pour travailler avec la connexion wifi et le calme environnant. Merci Patricia.",
  en:"The place is particularly well laid out and equipped. It's also tastefully decorated and very comfortable, set in a very pleasant environment. Patricia is an extremely welcoming host who really knows how to host. My colleague and I were delighted to spend our week there. It's also perfect for working, with the wifi connection and the surrounding calm. Thank you Patricia."} },

{ name:"Marc-Antoine", meta:{type:"tenure", years:7}, rating:5, date:{fr:"Décembre 2023", en:"December 2023"}, stay:"week",
  text:{fr:"Cette petite semaine chez Patricia était non seulement plus que fidèle aux photos et à la description, mais l'esprit cocooning du bungalow a rendu cette semaine merveilleuse. Nous conseillons vivement ce logement et remercions Patricia.",
  en:"This little week at Patricia's was not only more than true to the photos and description, but the cozy spirit of the bungalow made the week wonderful. We highly recommend this place and thank Patricia."} },

{ name:"Christine", meta:{type:"location", text:"Trois-Rivières, Canada"}, rating:5, date:{fr:"Avril 2023", en:"April 2023"}, stay:"week",
  text:{fr:"Un merveilleux petit bijou ! Patricia est une hôte très à l'écoute et proactive ! Elle s'assure que nous ne manquons de rien ! Elle nous accueille avec des petites attentions qui sont grandement appréciées. Dès que vous mettez les pieds dans la propriété, vous vous sentez dans un petit cocon très intime. Vous êtes à proximité des plus belles plages de l'île. Ce fut un réel bonheur d'avoir pu profiter du bungalow Serenity ! Un coup de cœur ! Et pour Patricia également !!",
  en:"A wonderful little gem! Patricia is a very attentive and proactive host! She makes sure we lack nothing! She welcomes us with little touches that are greatly appreciated. The moment you step onto the property, you feel wrapped in a very intimate cocoon. You're close to the island's most beautiful beaches. It was a real joy to enjoy Bungalow Serenity! An absolute favorite — and so is Patricia!!"} },

{ name:"Henrick", meta:{type:"tenure", years:10}, rating:5, date:{fr:"Février 2022", en:"February 2022"}, stay:"short",
  text:{fr:"Super logement, bien placé et sécurisé ! Sans compter l'hôte, Patricia, très réactive et à l'écoute ! Je recommande les yeux fermés !",
  en:"Great place, well located and secure! Not to mention the host, Patricia, very responsive and attentive! I recommend it with full confidence!"} },

{ name:"Eric", meta:{type:"tenure", years:10}, rating:5, date:{fr:"Mars 2022", en:"March 2022"}, stay:"long",
  text:{fr:"Le bungalow de Patricia est parfait, décoré avec goût et très bien situé dans une résidence sécurisée et proche des plus belles plages.",
  en:"Patricia's bungalow is perfect, tastefully decorated and very well located in a secure residence close to the most beautiful beaches."} },

{ name:"Jacky", meta:{type:"tenure", years:12}, rating:5, date:{fr:"Septembre 2022", en:"September 2022"}, stay:"long",
  text:{fr:"Le top. Bungalow 5 étoiles, confortable, bien équipé et décoré avec goût. Les hôtes sont charmants et réactifs. Tout est réuni pour que vous passiez un agréable séjour à Saint-Martin.",
  en:"Top notch. A 5-star bungalow, comfortable, well equipped and tastefully decorated. The hosts are charming and responsive. Everything is in place for a lovely stay in Saint-Martin."} },

{ name:"Léa", meta:{type:"location", text:"France"}, rating:5, date:{fr:"Janvier 2024", en:"January 2024"}, stay:"short",
  text:{fr:"Lieu exceptionnel ! Nous y reviendrons à chacun de nos séjours si c'est disponible. Le « bungalow » est une petite maison, idéalement située, spacieuse, décorée avec goût, très propre, et on s'y sent hyper bien. Vous y trouverez tout ce dont vous avez besoin pour un séjour parfait. On remercie notre super hôte pour les petites attentions, nous n'avons manqué de rien. La vue est tellement apaisante et le lotissement calme et sécurisé. Je recommande à 100% ce logement. Merci Patricia !",
  en:"Exceptional place! We'll come back to it every time we visit, if it's available. The 'bungalow' is a small house, ideally located, spacious, tastefully decorated, very clean, and you feel amazing there. You'll find everything you need for a perfect stay. Thanks to our superhost for the little extra touches — we lacked nothing. The view is so soothing and the development is calm and secure. I 100% recommend this place. Thank you Patricia!"} },

{ name:"Chloe", meta:{type:"tenure", years:12}, rating:5, date:{fr:"Juin 2022", en:"June 2022"}, stay:"short",
  text:{fr:"Superbe bungalow, communication au top. Propreté nickel. Je recommande les yeux fermés !",
  en:"Superb bungalow, top-notch communication. Spotlessly clean. I recommend it with full confidence!"} },

{ name:"Sylvain", meta:{type:"location", text:"Beloeil, Canada"}, rating:5, date:{fr:"Février 2023", en:"February 2023"}, stay:"long",
  text:{fr:"Très bel emplacement, calme, on a passé 52 jours mémorables avec un bungalow très bien équipé avec un BBQ. Il vous manque juste vos valises pour partir et vivre une expérience superbe, et Patricia est à l'écoute s'il y a un problème à régler.",
  en:"Beautiful, quiet location — we spent 52 memorable days in a bungalow that's very well equipped, with a BBQ. All you need is your suitcases to head off and have a wonderful experience, and Patricia is attentive if anything needs sorting out."} },

{ name:"Ruddy", meta:{type:"tenure", years:11}, rating:5, date:{fr:"Avril 2022", en:"April 2022"}, stay:"short",
  text:{fr:"Un sans faute ! Nous reviendrons.",
  en:"Flawless! We will be back."} },

{ name:"Amandine", meta:{type:"location", text:"Marigot, Saint-Martin"}, rating:5, date:{fr:"Juillet 2024", en:"July 2024"}, stay:"short",
  text:{fr:"Nous avons passé un excellent séjour.",
  en:"We had an excellent stay."} },

{ name:"Henrick", meta:{type:"location", text:"Petit-Bourg, Guadeloupe"}, rating:5, date:{fr:"Décembre 2022", en:"December 2022"}, stay:"short",
  text:{fr:"Second séjour et toujours aussi top. Je recommande à 100%.",
  en:"Second stay and still just as great. I 100% recommend it."} },

{ name:"Elise", meta:{type:"tenure", years:8}, rating:5, date:{fr:"Mai 2022", en:"May 2022"}, stay:"short",
  text:{fr:"Nous avons passé un excellent séjour... tout était parfait ! Merci, à bientôt !",
  en:"We had an excellent stay... everything was perfect! Thank you, see you soon!"} },

{ name:"Clemire", meta:{type:"location", text:"Case-Pilote, Martinique"}, rating:5, date:{fr:"Septembre 2022", en:"September 2022"}, stay:"week",
  text:{fr:"Séjour fabuleux, rien à redire.",
  en:"Fabulous stay, nothing to complain about."} },

{ name:"Ludivine", meta:{type:"location", text:"Le Lamentin, Martinique"}, rating:5, date:{fr:"Avril 2023", en:"April 2023"}, stay:"short",
  text:{fr:"Excellent séjour.",
  en:"Excellent stay."} },

{ name:"Eric", meta:{type:"location", text:"New York, États-Unis"}, rating:5, date:{fr:"Janvier 2025", en:"January 2025"}, stay:"short",
  text:{fr:"Cet endroit est vraiment à la hauteur de son nom ! Même s'il y a d'autres propriétés à proximité, on ne le devinerait jamais car c'est très calme et isolé. Le matin, le lever de soleil paisible nous a accueillis sur la terrasse, et la nuit, nous n'avons rien entendu d'autre que le chant des grenouilles arboricoles. Moderne, propre, spacieux et sécurisé. Grand lit confortable. La climatisation et les ventilateurs ont très bien fonctionné. Patricia est une hôte merveilleuse... sympathique, facile à vivre, arrangeante et attentive. Très réactive, des indications et des informations claires. Elle nous a accueillis à notre arrivée et nous a fait visiter le bungalow, en s'assurant que nous avions tout ce dont nous avions besoin. De petites touches attentionnées sont partout, et elle a anticipé presque tous les besoins. Nous avons vraiment apprécié notre séjour et espérons revenir !",
  en:"This place truly lives up to its name! Even though there are other properties nearby, you'd never know it — it's very quiet and secluded. In the morning, a peaceful sunrise greeted us on the terrace, and at night we heard nothing but tree frogs singing. Modern, clean, spacious and secure. Big, comfortable bed. The AC and fans worked very well. Patricia is a wonderful host... friendly, easygoing, accommodating and attentive. Very responsive, with clear directions and information. She welcomed us on arrival and showed us around the bungalow, making sure we had everything we needed. Thoughtful little touches are everywhere, and she anticipated almost every need. We really enjoyed our stay and hope to come back!"} },

{ name:"June", meta:{type:"tenure", years:3}, rating:5, date:{fr:"Mars 2024", en:"March 2024"}, stay:"week",
  text:{fr:"Le bungalow était mignon, calme, décoré avec goût et apaisant. Nous avons adoré l'emplacement ; il était à une courte distance de superbes plages et restaurants et nous nous sommes sentis très en sécurité dans ce lotissement sécurisé. La vue était magnifique. C'était parfait pour nous deux et il y avait tout le nécessaire. L'hôte est disponible et prête à répondre à vos questions ou préoccupations, et se surpasse pour rendre votre séjour exceptionnel. Nous recommanderons ce bungalow à nos amis et à notre famille. Merci encore pour cette expérience formidable !",
  en:"The bungalow was cute, quiet, tastefully decorated and soothing. We loved the location; it was a short distance from great beaches and restaurants, and we felt very safe in this secure development. The view was gorgeous. It was perfect for the two of us and had everything necessary. The host is available and ready to answer your questions or concerns, going above and beyond to make your stay exceptional. We'll recommend this bungalow to our friends and family. Thanks again for this wonderful experience!"} },

{ name:"Robert", meta:{type:"location", text:"Wauwatosa, Wisconsin"}, rating:5, date:{fr:"Mars 2025", en:"March 2025"}, stay:"long",
  text:{fr:"Si vous êtes à la recherche d'un endroit serein à Saint-Martin, ne cherchez pas plus loin. Les Terres Basses est un quartier résidentiel calme qui contraste fortement avec d'autres parties de l'île. Si vous voulez profiter des plaisirs de Saint-Martin, c'est le logement idéal. Vous pouvez visiter l'île et ses nombreuses plages et merveilleux restaurants, puis rentrer chez vous dans un endroit calme et serein. Patricia est une excellente hôte. Elle est très réactive à toutes les préoccupations ou suggestions concernant les restaurants, les activités, etc. Je ne pouvais pas demander un meilleur hôte. Le bungalow est très bien équipé et très propre. Elle fournit même des chaises longues, un parasol et des bouées. Il y a une belle véranda surplombant l'île — magique la nuit. Il y a des plages à proximité ou à quelques minutes en voiture (vous aurez besoin d'une voiture pour vous déplacer). Je ne peux que recommander la maison de Patricia pour son emplacement, son hospitalité et sa tranquillité.",
  en:"If you're looking for a serene spot in Saint-Martin, look no further. Terres Basses is a quiet residential area that sharply contrasts with other parts of the island. If you want to enjoy everything Saint-Martin has to offer, this is the ideal place. You can explore the island's many beaches and wonderful restaurants, then come home to a calm, serene spot. Patricia is an excellent host. She's very responsive to any concerns or suggestions about restaurants, activities, etc. I couldn't ask for a better host. The bungalow is very well equipped and very clean. She even provides sun loungers, a parasol and pool noodles. There's a lovely veranda overlooking the island — magical at night. Beaches are nearby or a short drive away (you'll need a car to get around). I can only recommend Patricia's home for its location, hospitality and tranquility."} },

{ name:"Mike", meta:{type:"location", text:"Mount Rainier, Maryland"}, rating:5, date:{fr:"Juillet 2022", en:"July 2022"}, stay:"short",
  text:{fr:"Lorsque je voyage à l'étranger, je préfère souvent vivre comme un habitant du lieu. Le bungalow de Patricia à Terres-Basses était vraiment comme si j'avais ma propre maison sur la merveilleuse île de Saint-Martin. La propriété est un bungalow magnifiquement décoré dans un quartier sécurisé. Je cherchais la sérénité, et c'est exactement ce que j'ai trouvé. Je suis végan, donc j'aime avoir une cuisine pour stocker ou cuisiner de la nourriture. La cuisine avait tout le nécessaire. Le salon dispose d'une enceinte Bluetooth pour écouter mes playlists de relaxation, la salle de bain était remplie de déodorant naturel, de savons, de shampoings et de répulsif anti-moustiques. Le lit était grand et confortable et chaque pièce disposait de ventilateurs de plafond et de la climatisation. Le matin, je prenais mon petit déjeuner à l'extérieur sur la terrasse. L'emplacement est également très pratique. Le village de Maho était à proximité, tout comme la plage de Cupecoy. Patricia n'aurait pas pu être plus accommodante et a rapidement résolu tous les malentendus. Ce logement est parfait.",
  en:"When I travel abroad, I often prefer to live like a local. Patricia's bungalow in Terres Basses really felt like having my own home on the wonderful island of Saint-Martin. The property is a beautifully decorated bungalow in a secure neighborhood. I was looking for serenity, and that's exactly what I found. I'm vegan, so I love having a kitchen to store or cook food, and the kitchen had everything necessary. The living room has a Bluetooth speaker for my relaxation playlists, and the bathroom was stocked with natural deodorant, soaps, shampoos and mosquito repellent. The bed was large and comfortable, and every room had ceiling fans and AC. In the morning I had breakfast outside on the terrace. The location is also very convenient — Maho village was nearby, as was Cupecoy beach. Patricia couldn't have been more accommodating and quickly resolved any misunderstandings. This place is perfect."} },

{ name:"Danielle", meta:{type:"location", text:"La Nouvelle-Orléans, Louisiane"}, rating:5, date:{fr:"Août 2022", en:"August 2022"}, stay:"short",
  text:{fr:"Cet endroit était parfait ! C'était dans un endroit calme et agréable, loin du bruit. C'était très paisible et exactement ce dont j'avais besoin ! Les équipements étaient parfaits et l'espace était très confortable. Le soir, sur la terrasse, nous nous sommes détendus et le haut-parleur a été une touche agréable. Je reviendrai certainement y séjourner quand je serai en ville.",
  en:"This place was perfect! It was in a quiet, pleasant spot, away from noise. Very peaceful and exactly what I needed! The amenities were perfect and the space was very comfortable. In the evening, on the terrace, we relaxed and the speaker was a nice touch. I will definitely stay here again when I'm in town."} },

{ name:"Emily", meta:{type:"location", text:"Stratford, Canada"}, rating:5, date:{fr:"Janvier 2025", en:"January 2025"}, stay:"long",
  text:{fr:"Nous avons passé un merveilleux moment chez Patricia. Il ressemble aux photos, est très confortable et dispose de tout ce dont vous avez besoin. L'emplacement est si paisible. Nous avons adoré le soleil sur la terrasse le matin et les étoiles la nuit. D'excellentes plages sont à quelques minutes. Patricia nous a accueillis à notre arrivée et nous a fait visiter. Elle s'est montrée extrêmement cordiale et réactive. Merci Patricia ! Nous serions ravis de revenir !",
  en:"We had a wonderful time at Patricia's. It looks just like the photos, is very comfortable and has everything you need. The location is so peaceful. We loved the morning sun on the terrace and the stars at night. Great beaches are just minutes away. Patricia welcomed us on arrival and showed us around. She was extremely cordial and responsive. Thank you Patricia! We would love to come back!"} },

{ name:"Dominik", meta:{type:"tenure", years:14}, rating:5, date:{fr:"Avril 2022", en:"April 2022"}, stay:"long",
  text:{fr:"Je voyage beaucoup et très rarement je dis « wow » quand j'entre dans la maison. Cet endroit était si beau, propre, bien équipé, confortable et agréable. On remarque immédiatement une grande attention aux détails. L'hôte a été super sympathique et très professionnel. L'emplacement était superbe. Nous avons vraiment apprécié tout notre séjour (quatre semaines) dès le premier jour. Hautement recommandé !",
  en:"I travel a lot and very rarely say 'wow' when walking into a place. This one was so beautiful, clean, well equipped, comfortable and pleasant. You immediately notice great attention to detail. The host was super friendly and very professional. The location was superb. We truly enjoyed our entire four-week stay from day one. Highly recommended!"} },

{ name:"Leila", meta:{type:"location", text:"Framingham, Massachusetts"}, rating:5, date:{fr:"Juillet 2024", en:"July 2024"}, stay:"week",
  text:{fr:"Accueil dès la première minute. Un séjour parfait : confortable, propre au grincement, tout ce dont nous pourrions avoir besoin, et situé dans le plus bel emplacement de l'île. Notre hôte Patricia s'est rendue disponible pour nous accueillir à notre arrivée, ce qui a rendu l'arrivée très facile. Le logement entier est impeccable, pas un grain de poussière. L'état est parfait comme sur les photos. Les équipements 100% naturels de la belle et spacieuse salle de bain étaient une touche agréable. Tout ce dont nous avions besoin était là : une télévision connectée, une cuisine bien équipée, une chambre spacieuse avec beaucoup d'espace de rangement, un lave-linge, des serviettes de plage et un canapé confortable pour se détendre. Terres Basses est le quartier le plus exclusif et le plus beau de l'île, et le bungalow est proche des 2 meilleures plages qui s'y trouvent. Tout cela a permis un séjour reposant ! Nous reviendrons certainement.",
  en:"Welcomed from the very first minute. A perfect stay: comfortable, spotlessly clean, everything we could need, and located in the island's most beautiful spot. Our host Patricia made herself available to welcome us on arrival, which made check-in very easy. The entire place is immaculate, not a speck of dust. It's exactly as pictured. The 100% natural amenities in the beautiful, spacious bathroom were a nice touch. Everything we needed was there: a smart TV, a well-equipped kitchen, a spacious bedroom with plenty of storage, a washing machine, beach towels and a comfy sofa to relax on. Terres Basses is the island's most exclusive and beautiful neighborhood, and the bungalow is close to its two best beaches. All of it made for a restful stay! We will definitely be back when we return to St-Martin."} },

{ name:"Alexander", meta:{type:"location", text:"New York, New York"}, rating:5, date:{fr:"Avril 2025", en:"April 2025"}, stay:"week",
  text:{fr:"Patricia a été une hôte absolument merveilleuse, et notre séjour a été tout ce que nous aurions pu demander. Le bungalow est entièrement privé, avec votre propre porche donnant sur une vue magnifique. Il y a une enceinte Bluetooth, une excellente climatisation et des ventilateurs, des produits de bain entièrement naturels, une cuisine avec tout ce dont vous pourriez avoir besoin. Que demander de plus ! Il est à 25 min à pied ou à 5 min en voiture d'une superbe plage, Baie aux Prunes, via les routes très privées et calmes des Terres Basses. Et une autre grande plage, Baie Rouge, est à 5 minutes en voiture par la route principale. La prochaine fois que nous retournerons à Saint-Martin, nous espérons que le logement de Patricia sera disponible, car nous ne voudrions pas séjourner ailleurs. Merci, Patricia !",
  en:"Patricia was an absolutely wonderful host, and our stay was everything we could have asked for. The bungalow is entirely private, with your own porch overlooking a beautiful view. There's a Bluetooth speaker, excellent AC and fans, fully natural bath products, and a kitchen with everything you could need. What more could you ask for! It's a 25-minute walk or 5-minute drive to a superb beach, Baie aux Prunes, via the very private and quiet roads of Terres Basses. Another great beach, Baie Rouge, is 5 minutes away by car via the main road. Next time we return to Saint-Martin, we hope Patricia's place will be available, because we wouldn't want to stay anywhere else. Thank you, Patricia!"} },

{ name:"Stephen", meta:{type:"tenure", years:4}, rating:5, date:{fr:"Novembre 2023", en:"November 2023"}, stay:"long",
  text:{fr:"Cadre magnifique, privé et calme. Patricia est très réactive et très accueillante. C'était notre deuxième séjour dans cette propriété et nous espérons revenir.",
  en:"Beautiful setting, private and quiet. Patricia is very responsive and very welcoming. This was our second stay at this property and we hope to return."} },

{ name:"Ioana Daniela", meta:{type:"tenure", years:8}, rating:5, date:{fr:"Décembre 2024", en:"December 2024"}, stay:"week",
  text:{fr:"Le bungalow était propre et bien entretenu, ce qui a rendu notre séjour très agréable. L'intimité était parfaite. Les hôtes étaient sympathiques. Très satisfaite, un emplacement idéal, et nous serions ravis d'être de retour.",
  en:"The bungalow was clean and well maintained, which made our stay very pleasant. Privacy was perfect. The hosts were friendly. Very satisfied, an ideal location, and we would love to come back."} },

{ name:"Karen", meta:{type:"location", text:"Toronto, Canada"}, rating:5, date:{fr:"Juillet 2022", en:"July 2022"}, stay:"short",
  text:{fr:"Cet endroit ressemble aux photos. Il est spacieux pour 2 personnes et dispose de tout le nécessaire. Magnifiques meubles et draps, la cuisine a des ustensiles de qualité, des assiettes, des appareils Smeg (bouilloire, presse-agrumes), un mousseur à lait, une machine Nespresso. Mélangeurs d'alcool gratuits, bière, eau et confitures, kit de bienvenue pour vous lancer. Excellents articles de toilette spa locaux. Canapé-lit pour une personne supplémentaire. Le patio/terrasse est idéal pour se détendre après une journée à la plage. Belle vue sur les lumières du lagon de Simpson au loin. Proche de Baie Longue, Baie Rouge et Baie aux Prunes dans le quartier des Terres Basses. Chaises de plage et bouées gratuites. Coffre-fort dans la chambre. Sécurité 24h/24 et le chalet dispose également d'un parking sécurisé. Meilleure pâtisserie très proche. Magasins de Marigot non loin non plus pour le vin, le fromage. Je le recommanderais vivement.",
  en:"This place looks just like the photos. It's spacious for 2 people and has everything necessary. Beautiful furniture and linens, the kitchen has quality utensils, dishware, Smeg appliances (kettle, citrus press), a milk frother, a Nespresso machine. Free drink mixers, beer, water and jams, a welcome kit to get you started. Excellent local spa toiletries. A sofa bed for an extra person. The patio/terrace is ideal for relaxing after a day at the beach. Beautiful view of the Simpson lagoon lights in the distance. Close to Baie Longue, Baie Rouge and Baie aux Prunes in the Terres Basses neighborhood. Free beach chairs and pool noodles. Safe in the bedroom. 24/7 security and the cottage also has secure parking. A great bakery is very close by, and Marigot's shops aren't far either for wine and cheese. I would highly recommend it."} },

{ name:"Kim", meta:{type:"tenure", years:7}, rating:5, date:{fr:"Mai 2023", en:"May 2023"}, stay:"week",
  text:{fr:"Notre séjour a été merveilleux. Patricia est une hôtesse super sympathique et fiable qui se surpassera pour vous assurer de passer un séjour agréable. Nous avons reçu des conseils sur de bons restaurants, et pour d'autres questions, nous avons obtenu des réponses très rapidement. De plus, le bungalow était incroyablement propre et très joliment décoré. Il ne manque rien dans le bungalow ; tout a été pensé. Je recommande vivement à d'autres personnes de séjourner ici si vous allez à Saint-Martin !",
  en:"Our stay was wonderful. Patricia is a super friendly and reliable host who will go above and beyond to make sure you have a pleasant stay. We got tips on good restaurants, and for other questions we got answers very quickly. The bungalow was also incredibly clean and beautifully decorated. Nothing is missing — everything has been thought of. I highly recommend staying here if you're going to Saint-Martin!"} },

{ name:"Heather", meta:{type:"location", text:"Lancaster, Pennsylvanie"}, rating:5, date:{fr:"Novembre 2024", en:"November 2024"}, stay:"short",
  text:{fr:"Calme et privé. L'emplacement était parfait pour nous permettre de nous rendre facilement sur différentes plages et bars/restaurants. Hôte très réactive et accommodante. Je séjournerai à nouveau dans le quartier.",
  en:"Quiet and private. The location was perfect for us to easily reach different beaches and bars/restaurants. Very responsive and accommodating host. I will stay in this neighborhood again."} },

{ name:"Kimberly", meta:{type:"location", text:"Sarasota, Floride"}, rating:5, date:{fr:"Octobre 2022", en:"October 2022"}, stay:"short",
  text:{fr:"Le cottage de Patricia est vraiment une oasis de sérénité entourée d'un feuillage tropical luxuriant. C'est calme, paisible et sécurisé. Le décor est charmant et moderne. La cuisine est bien approvisionnée avec tous les ustensiles nécessaires. Patricia a même eu la gentillesse d'inclure une bouteille de rosé et de l'eau fraîche. Un séjour absolument fabuleux et un rapport qualité-prix fantastique.",
  en:"Patricia's cottage is truly an oasis of serenity surrounded by lush tropical foliage. It's calm, peaceful and secure. The decor is charming and modern. The kitchen is well stocked with all the necessary utensils. Patricia was even kind enough to include a bottle of rosé and cold water. An absolutely fabulous stay and fantastic value for money."} },

{ name:"Sarah", meta:{type:"tenure", years:12}, rating:5, date:{fr:"Juin 2022", en:"June 2022"}, stay:"short",
  text:{fr:"Ne cherchez plus ! Si vous avez trouvé cette annonce, allez-y et réservez ! Patricia est une hôte merveilleuse et son logement est magnifiquement entretenu. Tout est si bien placé et fourni, bien au-delà des attentes, elle a pensé à tout ce qui était possible ! Vous aurez besoin d'une voiture pour vous déplacer, mais les plus belles plages ne sont qu'à quelques minutes. Il est facile de se rendre dans d'excellents restaurants et lieux grâce à la liste de recommandations de Patricia. De loin notre meilleure expérience Airbnb à ce jour. Merci infiniment :)",
  en:"Look no further! If you've found this listing, go ahead and book it! Patricia is a wonderful host and her place is beautifully maintained. Everything is so well placed and provided, far beyond expectations — she thought of everything possible! You'll need a car to get around, but the most beautiful beaches are just minutes away. It's easy to find great restaurants and places thanks to Patricia's list of recommendations. By far our best Airbnb experience to date. Thank you so much :)"} },

{ name:"Michelle", meta:{type:"tenure", years:8}, rating:5, date:{fr:"Juin 2024", en:"June 2024"}, stay:"long",
  text:{fr:"Un Airbnb d'une beauté incroyable ! Joli lit et douche ! Très beau bungalow avec tout ce que vous pourriez vouloir. Patricia est vraiment une hôtesse charmante qui est toujours là pour vous ! Je me sentais comme dans une résidence secondaire ! Vraiment parfait ! Hautement recommandé !",
  en:"An incredibly beautiful Airbnb! Lovely bed and shower! A very beautiful bungalow with everything you could want. Patricia is truly a charming host who is always there for you! It felt like a second home! Truly perfect! Highly recommended!"} },

{ name:"Johan", meta:{type:"tenure", years:12}, rating:5, date:{fr:"Février 2025", en:"February 2025"}, stay:"short",
  text:{fr:"C'est un bungalow magnifique. Tout est si propre et frais ! Nous avons reçu une aide illimitée en cas de besoin. Tout sentait bon, nous n'avons rien trouvé qui nous manquait. Je recommande vivement ce bel hébergement à Terres Basses.",
  en:"This is a beautiful bungalow. Everything is so clean and fresh! We received unlimited help whenever needed. Everything smelled nice, and we didn't find anything lacking. I highly recommend this beautiful accommodation in Terres Basses."} },

{ name:"Nick", meta:{type:"tenure", years:13}, rating:5, date:{fr:"Août 2024", en:"August 2024"}, stay:"short",
  text:{fr:"Propreté irréprochable, odeur délicieuse. Climatisation fabuleuse. Réponses super rapides de Jon. Beaucoup plus grand qu'il n'y paraît sur les photos. La qualité des équipements et du matériel était absolument irréprochable et tout ce dont vous auriez pu avoir besoin était fourni. La plage de Baie Rouge, à proximité, était merveilleusement exempte d'algues et constituait un endroit idéal pour se baigner, même après le passage de la tempête Ernesto.",
  en:"Impeccably clean, wonderful smell. Fabulous air conditioning. Super quick responses from Jon. Much bigger than it appears in the photos. The quality of the amenities and equipment was absolutely flawless and everything you could need was provided. Nearby Baie Rouge beach was wonderfully free of seaweed and a great place to swim, even in the conditions following storm Ernesto."} },

{ name:"Victor", meta:{type:"tenure", years:4}, rating:5, date:{fr:"Janvier 2024", en:"January 2024"}, stay:"short",
  text:{fr:"La vue est magnifique. C'est très privé, paisible et calme. Le logement lui-même est propre, organisé et dispose de tout le nécessaire. L'hôte a été très réactive et je reviendrai sûrement, rien ne se compare.",
  en:"The view is magnificent. It's very private, peaceful and quiet. The place itself is clean, organized and has everything necessary. The host was very responsive and I will surely be back — nothing compares."} },

{ name:"Lilia", meta:{type:"tenure", years:5}, rating:5, date:{fr:"Novembre 2023", en:"November 2023"}, stay:"week",
  text:{fr:"Nous avons passé un superbe moment ! Le bungalow est magnifique et bien aménagé, et disposait de toutes les commodités d'une maison ! Patricia est une hôte gracieuse et a toujours été disponible lorsque nous avions des questions.",
  en:"We had a wonderful time! The bungalow is beautiful and well laid out, with all the comforts of a home! Patricia is a gracious host and was always available whenever we had questions."} },

{ name:"Sujin", meta:{type:"location", text:"New York, New York"}, rating:5, date:{fr:"Mai 2024", en:"May 2024"}, stay:"short",
  text:{fr:"Nous avons vraiment apprécié notre séjour dans l'Airbnb de Patricia. C'était parfaitement propre, douillet, confortable et paisible. C'est une excellente option pour les séjours de longue durée. Nous reviendrions absolument séjourner ici et aimerions y rester plus longtemps !",
  en:"We really enjoyed our stay at Patricia's Airbnb. It was perfectly clean, cozy, comfortable and peaceful. It's a great option for long stays. We would absolutely come back and would love to stay even longer!"} },

{ name:"Vicki", meta:{type:"location", text:"Nixa, Missouri"}, rating:5, date:{fr:"Mars 2024", en:"March 2024"}, stay:"long",
  text:{fr:"L'hôte a été opérée et s'est rétablie pendant tout le mois de notre visite. Elle a quand même réussi à répondre rapidement à toutes les questions et a demandé à son co-hôte ou à son mari de répondre en personne. Ce fut des vacances parfaites et nous nous sentirons chanceux de revenir l'année prochaine. Je recommande vivement ! Je ne peux pas exprimer adéquatement notre gratitude !",
  en:"The host had surgery and was recovering during our entire month-long visit. She still managed to respond quickly to every question and had her co-host or husband answer in person. It was a PERFECT vacation and we'll feel lucky to return next year. I HIGHLY RECOMMEND! I can't adequately express our gratitude!"} },

{ name:"Aaron", meta:{type:"location", text:"Port of Spain, Trinité-et-Tobago"}, rating:5, date:{fr:"Décembre 2022", en:"December 2022"}, stay:"week",
  text:{fr:"Ce logement illustre l'atmosphère calme et décontractée du côté français de l'île. Résidence sécurisée, excellente et pittoresque, à proximité de restaurants, d'une station-service, de pharmacies, d'épiceries, de plages, etc. La maison est clairement conçue pour les couples, mais elle dispose d'un canapé escamotable dans l'espace de vie principal pour d'autres possibilités. Très propre et bien entretenu. Hôte très réactif qui parle français et anglais. Cette annonce est vivement recommandée !!",
  en:"This place captures the calm, relaxed atmosphere of the French side of the island. Secure, excellent and picturesque residence, close to restaurants, a gas station, pharmacies, grocery stores, beaches, etc. The house is clearly designed for couples, but has a pull-out sofa in the main living space for other possibilities. Very clean and well maintained. Very responsive host who speaks French and English. This listing is highly recommended!!"} },

{ name:"Fred", meta:{type:"location", text:"San Francisco, Californie"}, rating:5, date:{fr:"Mars 2024", en:"March 2024"}, stay:"long",
  text:{fr:"Le bungalow de Patricia est tout simplement spectaculaire. En tant qu'hôtesse, elle crée une expérience incroyable pour ses voyageurs. Elle est réactive, sympathique et claire. La propriété semble privée et paisible. Elle dispose d'un décor accueillant sur le thème des maisons de plage, avec des meubles élégants et des couleurs apaisantes. Patricia ajoute des petites attentions pour bien commencer votre expérience. La maison était impeccablement propre à notre arrivée. Les équipements sont luxueux. De nombreuses serviettes sont fournies, y compris de grandes serviettes de bain et de très grandes serviettes de plage. Les produits de toilette inclus sont respectueux de l'environnement et sentent très bon. La pression de l'eau est également excellente. La cuisine est bien équipée pour cuisiner des repas à la maison, avec de nombreux équipements pratiques que vous ne trouverez pas dans la plupart des Airbnb. Comme beaucoup d'autres objets dans sa maison, la vaisselle est magnifique. Le lit king-size est exceptionnellement confortable, avec beaucoup de couvertures et d'oreillers au choix et une literie douce et douillette. Si vous prévoyez de travailler à distance, il y a un petit bureau, et internet est ultra-rapide !",
  en:"Patricia's bungalow is simply spectacular. As a host, she creates an incredible experience for her guests. She's responsive, friendly and clear. The property feels private and peaceful, with a welcoming beach-house-themed decor, elegant furniture and soothing colors. Patricia adds little touches to get your stay off to a great start. The house was impeccably clean on arrival. The amenities are luxurious — plenty of towels are provided, including large bath towels and extra-large beach towels. The included toiletries are eco-friendly and smell wonderful. Water pressure is also excellent. The kitchen is well equipped for cooking meals at home, with many practical items you won't find in most Airbnbs. Like many other things in her house, the dishware is beautiful. The king-size bed is exceptionally comfortable, with plenty of blankets and pillows to choose from and soft, cozy bedding. If you're planning to work remotely, there's a small desk, and the internet is ultra-fast!"} },

{ name:"Mar", meta:{type:"tenure", years:11}, rating:5, date:{fr:"Novembre 2023", en:"November 2023"}, stay:"week",
  text:{fr:"C'est un magnifique bungalow avec beaucoup d'intimité. Tout ce que vous pouviez imaginer était présent ! Nous nous sommes sentis comme chez nous. Patricia a été une excellente hôte qui a tout fait pour nous ravir.",
  en:"This is a beautiful, very private bungalow. Everything you could imagine was there! We felt right at home. Patricia was an excellent host who did everything to delight us."} },

{ name:"Patrick", meta:{type:"location", text:"San Antonio, Texas"}, rating:5, date:{fr:"Août 2024", en:"August 2024"}, stay:"short",
  text:{fr:"La communication avant l'arrivée avec des instructions détaillées était parfaite. J'ai été accueilli à mon arrivée et j'ai reçu tous les détails nécessaires sur le bungalow et un aperçu général des commodités locales. Le bungalow est extrêmement propre, bien approvisionné et en très bon état. L'emplacement est si paisible, serein et relaxant avec un accès facile à la route principale vers Cupecoy ou Marigot. Une promenade matinale quotidienne jusqu'à la plage est un incontournable. Si vous préférez, c'est un trajet en voiture très rapide vers quelques belles plages. Patricia a été accommodante et a répondu à toutes mes questions. Hautement recommandé pour un séjour reposant à Saint-Martin.",
  en:"Communication before arrival with detailed instructions was perfect. I was welcomed on arrival and given all the necessary details about the bungalow and a general overview of local amenities. The bungalow is extremely clean, well stocked and in very good condition. The location is so peaceful, serene and relaxing, with easy access to the main road to Cupecoy or Marigot. A daily morning walk to the beach is a must. If you prefer, it's a very quick drive to a few beautiful beaches. Patricia was accommodating and answered all my questions. Highly recommended for a restful stay in Saint-Martin."} },

{ name:"Ryan", meta:{type:"location", text:"Westwood, New Jersey"}, rating:5, date:{fr:"Février 2022", en:"February 2022"}, stay:"short",
  text:{fr:"Magnifiquement décoré, soigneusement aménagé et situé au centre dans un quartier calme. Patricia a été extrêmement gentille et serviable pendant notre séjour.",
  en:"Beautifully decorated, carefully furnished and centrally located in a quiet neighborhood. Patricia was extremely kind and helpful during our stay."} },

{ name:"Francoise", meta:{type:"location", text:"Ottawa, Canada"}, rating:5, date:{fr:"Avril 2023", en:"April 2023"}, stay:"week",
  text:{fr:"Belle oasis pour se détendre, avec une décoration de bon goût et un souci du détail pour passer un séjour agréable. Nous adorons toujours Terres Basses en raison de sa sécurité à l'entrée de la résidence et de l'accès à 3 belles plages. Patricia répond très rapidement et nous a fait nous sentir les bienvenus au bungalow Serenity. Nous le recommanderons à nos amis et à notre famille.",
  en:"A lovely oasis to relax in, with tasteful decor and careful attention to detail for an enjoyable stay. We always love Terres Basses for its secured entrance and access to 3 beautiful beaches. Patricia replies very quickly and made us feel welcome at Bungalow Serenity. We will recommend it to our friends and family."} },

{ name:"Ellie", meta:{type:"location", text:"New York, New York"}, rating:5, date:{fr:"Août 2022", en:"August 2022"}, stay:"short",
  text:{fr:"Endroit superbe !!! Avec une terrasse magnifique. Nous avons eu quelques difficultés à le localiser et les hôtes ont été très gentils et serviables. Le logement était confortable et parfait pour notre séjour. Je reviendrais certainement !",
  en:"Superb place!!! With a magnificent terrace. We had a bit of trouble finding it and the hosts were very kind and helpful. The place was comfortable and perfect for our stay. I would definitely come back!"} },

{ name:"Sarita", meta:{type:"location", text:"Durham, Canada"}, rating:5, date:{fr:"Décembre 2023", en:"December 2023"}, stay:"short",
  text:{fr:"Le bungalow est parfait pour un couple. Propre et idéalement situé dans un quartier calme.",
  en:"The bungalow is perfect for a couple. Clean and ideally located in a quiet neighborhood."} },

{ name:"Nadege", meta:{type:"location", text:"Silver Spring, Maryland"}, rating:5, date:{fr:"Juin 2024", en:"June 2024"}, stay:"short",
  text:{fr:"Patricia est une hôtesse aimable, toujours en avance sur les besoins de ses voyageurs. Le bungalow est incroyable. Patricia a pensé à tout pour que votre séjour au bungalow Serenity soit mémorable. Je recommande vivement et elle se soucie vraiment de ses voyageurs.",
  en:"Patricia is a kind host, always one step ahead of her guests' needs. The bungalow is amazing. Patricia has thought of everything to make your stay at Bungalow Serenity memorable. I highly recommend it, and she truly cares about her guests."} },

{ name:"Fabio", meta:{type:"tenure", years:11}, rating:5, date:{fr:"Janvier 2024", en:"January 2024"}, stay:"long",
  text:{fr:"Logement paisible et reposant, décoré avec goût. Patricia s'est occupée de tous les détails et de tous les équipements pour nous garantir un séjour sans problème. Nous nous ferons un plaisir de revenir et de le recommander à nos amis !",
  en:"Peaceful and restful place, tastefully decorated. Patricia took care of every detail and every amenity to guarantee us a hassle-free stay. We'll be happy to come back and recommend it to our friends!"} },

{ name:"Fabian", meta:{type:"location", text:"Los Angeles, Californie"}, rating:5, date:{fr:"Juillet 2023", en:"July 2023"}, stay:"week",
  text:{fr:"Le gîte de Patricia est très agréable et calme, très bien situé, très propre et avec un mobilier moderne. Je recommande vivement de séjourner ici !",
  en:"Patricia's place is very pleasant and quiet, very well located, very clean and with modern furniture. I highly recommend staying here!"} },

{ name:"Patrick", meta:{type:"location", text:"Fort Myers, Floride"}, rating:5, date:{fr:"Août 2023", en:"August 2023"}, stay:"short",
  text:{fr:"L'endroit était merveilleux. Cadre très privé.",
  en:"The place was wonderful. Very private setting."} },

{ name:"Stephen", meta:{type:"tenure", years:4}, rating:5, date:{fr:"Octobre 2024", en:"October 2024"}, stay:"long",
  text:{fr:"On revient. Patricia est une hôte incroyable. Le cadre est paisible et privé.",
  en:"We're coming back. Patricia is an amazing host. The setting is peaceful and private."} },

{ name:"Stephen", meta:{type:"tenure", years:4}, rating:5, date:{fr:"Mars 2023", en:"March 2023"}, stay:"long",
  text:{fr:"Je reviendrai. Vivement recommandé. Patricia fournit des réponses immédiates.",
  en:"I will be back. Highly recommended. Patricia gives immediate responses."} },

{ name:"Chloé", meta:{type:"location", text:"Montréal, Canada"}, rating:5, date:{fr:"Janvier 2022", en:"January 2022"}, stay:"long",
  text:{fr:"Je n'aurais pas pu être mieux, notre séjour était incroyable ! L'hôte a été très accueillant et a répondu très rapidement à toutes les questions. Le bungalow était beau, propre, confortable et entièrement équipé avec tout ce dont nous avions besoin pour notre voyage de 1 mois. Patricia était tellement méticuleuse sur tout pour rendre notre séjour incroyable. Nous avons reçu beaucoup de cadeaux de bienvenue de la part de l'hôte. Il est très proche des attractions touristiques et à proximité de tous les beaux restaurants et marchés de la région — à 7 minutes en voiture. Particulièrement proche de mes plages préférées de l'île : Baie Longue et Baie aux Mullet. Nous avons eu le plaisir de rencontrer ses animaux de compagnie Léo le chat et Boris le chien à 3 pattes. Animaux très sympathiques. Nous avons passé un super séjour, nous reviendrons bientôt à 100%. Je recommande vivement d'y séjourner !",
  en:"I couldn't have asked for better, our stay was incredible! The host was very welcoming and answered all questions very quickly. The bungalow was beautiful, clean, comfortable and fully equipped with everything we needed for our one-month trip. Patricia was so meticulous about everything to make our stay amazing. We received lots of welcome gifts from the host. It's very close to tourist attractions and near all the great restaurants and markets in the area — a 7-minute drive. Particularly close to my favorite beaches on the island: Baie Longue and Mullet Bay. We had the pleasure of meeting her pets, Leo the cat and Boris the three-legged dog — very friendly animals. We had a great stay, we will 100% be back soon. I highly recommend staying here!"} },

{ name:"Paola", meta:{type:"tenure", years:11}, rating:5, date:{fr:"Décembre 2023", en:"December 2023"}, stay:"week",
  text:{fr:"Maison charmante équipée de tout le confort. Lieu parfait, silencieux. Patricia, hôte charmante. Je le recommande vraiment à tout le monde. Je reviendrai dès que possible.",
  en:"Charming home equipped with every comfort. Perfect, quiet spot. Patricia, a charming host. I really recommend it to everyone. I'll be back as soon as possible."} },

{ name:"Claudia", meta:{type:"tenure", years:7}, rating:5, date:{fr:"Mars 2023", en:"March 2023"}, stay:"week",
  text:{fr:"Le bungalow est très agréable et bien entretenu, il est spacieux et équipé de tout le confort. Nous avons passé un très bon moment : le calme est un plus, tout comme l'accueil et la disponibilité de Patricia. Très bon rapport qualité-prix.",
  en:"The bungalow is very pleasant and well maintained, spacious and equipped with every comfort. We had a great time: the quiet is a real plus, as is Patricia's welcome and availability. Very good value for money."} },

{ name:"Lawrence", meta:{type:"location", text:"Tchéquie"}, rating:5, date:{fr:"Août 2023", en:"August 2023"}, stay:"short",
  text:{fr:"Parfait.",
  en:"Perfect."} }
];
